FROM rockylinux:8
LABEL maintainer=henri@dhcpy6d.de

# get build requirements
RUN yum -y install createrepo \
                   git \
                   gpg \
                   python3-devel \
                   python3-docutils \
                   rpm-build \
                   rpm-sign \
                   sudo \
                   which

# flexible entrypoint, mounted as volume
ENTRYPOINT ["/entrypoint.sh"]